# Generated by Django 5.2.11 on 2026-02-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
