# Generated by Django 5.2.11 on 2026-02-23 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
