# Generated by Django 5.2.6 on 2026-05-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium',
            old_name='bailing_cycle',
            new_name='billing_cycle',
        ),
    ]
