# Generated by Django 5.2.14 on 2026-05-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department_name',
            field=models.CharField(default='Unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
