# Generated by Django 5.2.14 on 2026-05-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_department_name_student_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
