# Generated by Django 5.2.15 on 2026-06-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('processor_brand', models.CharField(max_length=100)),
                ('processor_model', models.CharField(max_length=200)),
                ('processor_generation', models.CharField(blank=True, max_length=100)),
                ('ram_size', models.PositiveIntegerField(help_text='RAM size in GB')),
                ('ram_type', models.CharField(max_length=50)),
                ('storage_size', models.PositiveIntegerField(help_text='Storage size in GB')),
                ('storage_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('NVME', 'NVME')], max_length=50)),
                ('gpu_brand', models.CharField(blank=True, max_length=100)),
                ('gpu_model', models.CharField(blank=True, max_length=200)),
                ('display_size', models.DecimalField(decimal_places=1, help_text='Inches', max_digits=4)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('refresh_rate', models.PositiveIntegerField(default=60, help_text='Hz')),
                ('panel_type', models.CharField(blank=True, max_length=50)),
                ('touchscreen', models.BooleanField(default=False)),
                ('battery_capacity', models.CharField(blank=True, max_length=100)),
                ('battery_life', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in KG', max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('wifi', models.BooleanField(default=True)),
                ('bluetooth', models.BooleanField(default=True)),
                ('usb_ports', models.PositiveIntegerField(default=0)),
                ('usb_type_c_ports', models.PositiveIntegerField(default=0)),
                ('hdmi_ports', models.PositiveIntegerField(default=0)),
                ('webcam', models.BooleanField(default=True)),
                ('microphone', models.BooleanField(default=True)),
                ('main_image', models.ImageField(upload_to='laptops/main/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laptops/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='laptop.laptop')),
            ],
        ),
    ]
